services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: ejemplo-db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "usuario", "-pusuario123"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ejemplo-db

  frontend:
      build: ./frontend
      ports:
        - "80:80"
      depends_on:
        - backend

volumes:
  mysql_data:

